### ISSUE TITLE
Enriquecimiento de la documentación

### ISSUE THREAD

**Issue by jmfernandez** [pcubilescid/Dominios#1]
Como el fichero README.md es la carta de presentación de tu proyecto en GitHub, aprovecha para introducir ahí todo lo que sea relevante para que cualquiera sea capaz de usar tus desarrollos en las mismas condiciones en las que los probaste.

Por ejemplo, una de mis sugerencias puedes introducir información más detallada sobre los organismos, como su identificador taxonómico, y un hiperenlace a su página en NCBI Taxonomy.

Otra sugerencia es que puedes describir qué conjuntos de datos has usado para probar cada uno de tus programas, así como incluír los enlaces directos de descarga.

**Comment by pcubilescid** [comment]
Estos datos han sido añadidos
