### ISSUE TITLE
Control del número de parámetros en los programas

### ISSUE THREAD

**Issue by jmfernandez** [pcubilescid/Dominios#4]
Cuando he ido a ejecutar `Proteinas_1Organismo_Fasta.py` sin parámetros me he encontrado con que se ha quejado el programa:

```
(venv) jfernan1@bsclife013[12]:/tmp/Dominios> python Proteinas_1Organismo_Fasta.py 
Traceback (most recent call last):
  File "Proteinas_1Organismo_Fasta.py", line 51, in <module>
    readUniProt(sys.argv[1],sys.argv[2],sys.argv[3])
IndexError: list index out of range
```

Para que esto no pase, el programa debe comprobar si tiene suficientes parámetros para ejecutar. Y si no los tuviese, entonces puede imprimir una descripción breve de qué parámetros espera (como habrás visto en otros programas de línea de comandos)

**Comment by pcubilescid** [comment]
Esta mejora ya ha sido modificada

**Comment by pcubilescid** [comment]
Esta mejora ha sido modificada
